name: Deploy to Azure Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage using inlineScript
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob service-properties update \
              --account-name csg1003200582970a18 \
              --static-website \
              --index-document index.html \
              --404-document error.html

            az storage blob upload \
              --account-name csg1003200582970a18 \
              --container-name '$web' \
              --name index.html \
              --file index.html \
              --auth-mode login

            az storage blob list \
              --account-name csg1003200582970a18 \
              --container-name '$web' \
              --output table \
              --auth-mode login
